export default [
  {
    preset: "Basic Kanban",
    boardName: "",
    columnsLocked: false,
    columns: [
      {
        name: "To Do",
        locked: true,
        isDragging: false,
        startX: 0,
        startY: 0,
        x: 0,
        y: 0,
        draggingOver: "",
        tasks: [],
      },
      {
        name: "In Progress",
        locked: true,
        isDragging: false,
        startX: 0,
        startY: 0,
        x: 0,
        y: 0,
        draggingOver: "",
        tasks: [],
      },
      {
        name: "Done",
        locked: true,
        isDragging: false,
        startX: 0,
        startY: 0,
        x: 0,
        y: 0,
        draggingOver: "",
        tasks: [],
      },
    ],
  },
  {
    preset: "Kanban",
    boardName: "",
    columnsLocked: false,
    columns: [
      {
        name: "Backlog",
        locked: true,
        isDragging: false,
        startX: 0,
        startY: 0,
        x: 0,
        y: 0,
        draggingOver: "",
        tasks: [],
      },
      {
        name: "Waiting",
        locked: true,
        isDragging: false,
        startX: 0,
        startY: 0,
        x: 0,
        y: 0,
        draggingOver: "",
        tasks: [],
      },
      {
        name: "Ready",
        locked: true,
        isDragging: false,
        startX: 0,
        startY: 0,
        x: 0,
        y: 0,
        draggingOver: "",
        tasks: [],
      },
      {
        name: "In Progress",
        locked: true,
        isDragging: false,
        startX: 0,
        startY: 0,
        x: 0,
        y: 0,
        draggingOver: "",
        tasks: [],
      },
      {
        name: "Done",
        locked: true,
        isDragging: false,
        startX: 0,
        startY: 0,
        x: 0,
        y: 0,
        draggingOver: "",
        tasks: [],
      },
    ],
  },
];
